### ISSUE TITLE
Specify the Node.js and other dependencies versions the library is compatible with

### ISSUE THREAD

**Issue by Eireen** [do-/dia.js#75]
В документации следует указать версии Node.js и других внешних зависимостей, с которыми совместима библиотека.

**Comment by do-** [comment]
Would it be enough?

https://github.com/do-/dia.js/wiki/%D0%9E%D0%B1%D1%89%D0%B8%D0%B5-%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%B0%2C-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8-%D0%B8-%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8

**Comment by do-** [comment]
Would you mind to discuss this topic via Telegram?

**Comment by Eireen** [comment]
https://t.me/EireenK
