### ISSUE TITLE
It's not clear how to do a pull request to the wiki 

### ISSUE THREAD

**Issue by Eireen** [do-/dia.js#76]
Непонятно, как предлагать изменения в Github-вику. Например, исправлять опечатки. Может, рассмотреть перенос вики в отдельный репозиторий или в подкаталог `docs` в коде проекта?
Попробовала метод [отсюда](https://stackoverflow.com/a/56810747), но вика у меня не форкается вместе с основным репом (пустая).

**Comment by do-** [comment]
It depends on your involvement level.

If you are ready to rewrite and then maintain the docs, the best option is to fork the entire wiki tree.

For occasional fixes, I'd better give you collaborator rights.

**Comment by Eireen** [comment]
@do- I'm not going to rewrite the wiki yet, just minor edits. So I'll be glad to get the rights of a collaborator to fix bugs and other little things.

**Comment by do-** [comment]
Added. Check for invite.
