### ISSUE TITLE
Can't find `to_validation_error` method definition - seems to be a bug

### ISSUE THREAD

**Issue by Eireen** [do-/dia.js#77]
https://github.com/do-/dia.js/blob/master/Content/Handler/HTTP/JsonRpc.js#L102

**Comment by do-** [comment]
Yep, it is.

The sole project (I know) using JsonRpc never gone production. That's why I missed it from remaking the logging/error handling some time ago.

I'd better drop this junk code. Or maybe you need it?

**Comment by do-** [comment]
Dropped.

https://github.com/do-/dia.js/commit/fa8faf9253ed53cbc57c2c1e0b7d9bdfc7cbd148
